use_chatgpt_api: true
allowed_telegram_usernames: []  # if empty, the bot is available to anyone
new_dialog_timeout: 600  # new dialog starts after timeout (in seconds)
# local path where to store MongoDB
MONGODB_PATH: ./mongodb
# MongoDB url
MONGODB_URL: mongodb://mongo:27017

# Mongo Express port
MONGO_EXPRESS_PORT: 8081
# Mongo Express username
MONGO_EXPRESS_USERNAME: username
# Mongo Express password
MONGO_EXPRESS_PASSWORD: password